// GENERATED by scripts/derive-matte.ts — do not edit; re-run the script.
export const MATTE = {
  ready: true,
  source: 'design/reference/matte-surface.jpg',
  sha256: '84f49d0afbf18d46bc6ab4e6b94c1c4cc320cbd6a661e004a2c4015321a663a9',
  surface: '#262626',
  grainSigma: 5.04,
} as const
