/* GENERATED by scripts/gen-roadmap.ts from content/features.ts — do not edit. 2026-10-01 */
export type RoadmapRow = { id: string; title: string; space: string; status: 'Being built' | 'Planned' }
export const ROADMAP: readonly RoadmapRow[] = [
  {
    "id": "FND-03",
    "title": "Enforce the internal-only configuration",
    "space": "enterprise",
    "status": "Being built"
  },
  {
    "id": "FND-07",
    "title": "Subscription billing for studios",
    "space": "platform",
    "status": "Being built"
  },
  {
    "id": "FND-08",
    "title": "Seat and client-company limits enforced (storage already is)",
    "space": "platform",
    "status": "Being built"
  },
  {
    "id": "FND-11",
    "title": "A studio’s own sending domain",
    "space": "platform",
    "status": "Planned"
  },
  {
    "id": "FND-14",
    "title": "Ledger events for file deletion, contracts and screening links",
    "space": "platform",
    "status": "Being built"
  },
  {
    "id": "MSG-07",
    "title": "Search across every room a person can see",
    "space": "messaging",
    "status": "Being built"
  },
  {
    "id": "MSG-22",
    "title": "Meeting-intent detection in conversation",
    "space": "messaging",
    "status": "Planned"
  },
  {
    "id": "MSG-23",
    "title": "Thread summaries and translation",
    "space": "messaging",
    "status": "Planned"
  },
  {
    "id": "MSG-24",
    "title": "Canvases",
    "space": "messaging",
    "status": "Planned"
  },
  {
    "id": "MSG-25",
    "title": "Cross-room answers with citations",
    "space": "messaging",
    "status": "Planned"
  },
  {
    "id": "CLI-06",
    "title": "Per-client brand kits",
    "space": "client",
    "status": "Planned"
  },
  {
    "id": "CLI-07",
    "title": "A custom portal domain per studio",
    "space": "client",
    "status": "Planned"
  },
  {
    "id": "CLI-09",
    "title": "Forensic watermarking",
    "space": "client",
    "status": "Planned"
  },
  {
    "id": "CLI-10",
    "title": "Release on payment",
    "space": "client",
    "status": "Planned"
  },
  {
    "id": "APR-06",
    "title": "Outside stakeholders and shareholders as approvers",
    "space": "review",
    "status": "Being built"
  },
  {
    "id": "APR-07",
    "title": "Sequential and parallel stages that behave differently",
    "space": "review",
    "status": "Being built"
  },
  {
    "id": "APR-09",
    "title": "A document approval frozen at the moment it is sent",
    "space": "review",
    "status": "Being built"
  },
  {
    "id": "APR-10",
    "title": "A script shown inside its approval",
    "space": "review",
    "status": "Being built"
  },
  {
    "id": "APR-11",
    "title": "Comments anchored to a script block, a panel or a region",
    "space": "review",
    "status": "Being built"
  },
  {
    "id": "MTG-03",
    "title": "A real Today view",
    "space": "meetings",
    "status": "Being built"
  },
  {
    "id": "MTG-05",
    "title": "Schedule a meeting from inside the message hub",
    "space": "meetings",
    "status": "Being built"
  },
  {
    "id": "MTG-06",
    "title": "External calendar sync",
    "space": "meetings",
    "status": "Planned"
  },
  {
    "id": "MTG-07",
    "title": "Round-robin and collective booking",
    "space": "meetings",
    "status": "Planned"
  },
  {
    "id": "MTG-08",
    "title": "Meeting transcripts",
    "space": "meetings",
    "status": "Planned"
  },
  {
    "id": "MTG-09",
    "title": "A meeting summary posted to the room",
    "space": "meetings",
    "status": "Planned"
  },
  {
    "id": "DOC-07",
    "title": "Contract reminders and expiry",
    "space": "documents",
    "status": "Being built"
  },
  {
    "id": "DOC-08",
    "title": "Start-work paperwork — deal memos, NDAs and releases per crew member",
    "space": "documents",
    "status": "Planned"
  },
  {
    "id": "MON-07",
    "title": "Spend, burn, margin and limits in one view",
    "space": "money",
    "status": "Being built"
  },
  {
    "id": "MON-08",
    "title": "Escrow payments through a licensed partner",
    "space": "money",
    "status": "Planned"
  },
  {
    "id": "MON-09",
    "title": "Timecards with overtime",
    "space": "money",
    "status": "Planned"
  },
  {
    "id": "CRW-10",
    "title": "Location library",
    "space": "crew",
    "status": "Planned"
  },
  {
    "id": "LOG-01",
    "title": "Notes kept across the Crew space, the Client space and every portal",
    "space": "notes",
    "status": "Being built"
  },
  {
    "id": "LOG-02",
    "title": "Summaries of logs, chats and meetings",
    "space": "notes",
    "status": "Planned"
  },
  {
    "id": "LOG-03",
    "title": "Ask about anything said in a chat or meeting, respecting permissions exactly",
    "space": "notes",
    "status": "Planned"
  },
  {
    "id": "SWR-03",
    "title": "Revision mode — coloured pages, asterisks, omitted scenes",
    "space": "suite",
    "status": "Planned"
  },
  {
    "id": "SWR-04",
    "title": "Final Draft (FDX) import and export",
    "space": "suite",
    "status": "Planned"
  },
  {
    "id": "SWR-05",
    "title": "Import from Fountain, PDF and Word",
    "space": "suite",
    "status": "Planned"
  },
  {
    "id": "SWR-07",
    "title": "Live co-editing for storyboards and workflows",
    "space": "suite",
    "status": "Planned"
  },
  {
    "id": "SWR-08",
    "title": "An assistant that learns one writer’s own style, with consent",
    "space": "suite",
    "status": "Planned"
  },
  {
    "id": "SWR-09",
    "title": "Storyboard frame generation",
    "space": "suite",
    "status": "Planned"
  },
  {
    "id": "SWR-10",
    "title": "Shot lists feeding the schedule",
    "space": "suite",
    "status": "Planned"
  },
  {
    "id": "SWR-11",
    "title": "Storyboard frame generation and animatics",
    "space": "suite",
    "status": "Being built"
  },
  {
    "id": "SWR-12",
    "title": "Workflows — generation pipelines and automations you compose",
    "space": "suite",
    "status": "Planned"
  },
  {
    "id": "NEW-01",
    "title": "Moodboards — references, looks and palettes, pinned to the production",
    "space": "suite",
    "status": "Planned"
  },
  {
    "id": "NEW-02",
    "title": "Hybrid production — live action and generated shots in one cut, with rights on both",
    "space": "generation",
    "status": "Being built"
  },
  {
    "id": "STG-01",
    "title": "The Stage — image and video generation, takes, versions, cost per result",
    "space": "generation",
    "status": "Being built"
  },
  {
    "id": "STG-02",
    "title": "Every major model through one gate — routed by what the shot needs",
    "space": "generation",
    "status": "Being built"
  },
  {
    "id": "STG-05",
    "title": "Provenance written for every generated image and video",
    "space": "generation",
    "status": "Being built"
  },
  {
    "id": "STG-07",
    "title": "Continuity — character, location, wardrobe and style held across every shot",
    "space": "generation",
    "status": "Planned"
  },
  {
    "id": "STG-08",
    "title": "Model Arena — the same prompt through several models, side by side",
    "space": "generation",
    "status": "Planned"
  },
  {
    "id": "STG-09",
    "title": "Studio Kits — your studio’s looks, characters and presets, reusable",
    "space": "generation",
    "status": "Planned"
  },
  {
    "id": "STG-10",
    "title": "Remaster — upscale and restore existing footage",
    "space": "generation",
    "status": "Planned"
  },
  {
    "id": "STG-11",
    "title": "Translation with lip-sync",
    "space": "generation",
    "status": "Planned"
  },
  {
    "id": "STG-12",
    "title": "Aspect-ratio conversion at any length",
    "space": "generation",
    "status": "Planned"
  },
  {
    "id": "STG-13",
    "title": "Variant output — cutdowns, captions, localisations",
    "space": "generation",
    "status": "Planned"
  },
  {
    "id": "STG-15",
    "title": "3D scenes from generated imagery",
    "space": "generation",
    "status": "Planned"
  },
  {
    "id": "SND-01",
    "title": "Sound — music, effects and dialogue generation",
    "space": "sound",
    "status": "Planned"
  },
  {
    "id": "SND-02",
    "title": "Sound design — spotting, ADR, mix",
    "space": "sound",
    "status": "Planned"
  },
  {
    "id": "SND-03",
    "title": "A licensed effects library",
    "space": "sound",
    "status": "Planned"
  },
  {
    "id": "PST-01",
    "title": "Edit — an assembly surface for the cut",
    "space": "post",
    "status": "Planned"
  },
  {
    "id": "PST-02",
    "title": "Timeline hand-off to professional editors, and back",
    "space": "post",
    "status": "Planned"
  },
  {
    "id": "PST-03",
    "title": "A full editor with two-way live sync",
    "space": "post",
    "status": "Planned"
  },
  {
    "id": "PST-04",
    "title": "Finishing — colour, grade, delivery specifications, captions",
    "space": "post",
    "status": "Planned"
  },
  {
    "id": "S3D-01",
    "title": "Studio — full 3D virtual sets",
    "space": "sets",
    "status": "Planned"
  },
  {
    "id": "S3D-02",
    "title": "Roamable interactive sets for a whole film",
    "space": "sets",
    "status": "Planned"
  },
  {
    "id": "S3D-03",
    "title": "Hire a film architect to build the set",
    "space": "sets",
    "status": "Planned"
  },
  {
    "id": "AGT-02",
    "title": "Per-organization AI keys",
    "space": "generation",
    "status": "Being built"
  },
  {
    "id": "AGT-03",
    "title": "Agents — executive producer and director agents",
    "space": "sets",
    "status": "Planned"
  },
  {
    "id": "TOP-01",
    "title": "Marketplace — licensing likenesses, avatars and voices, with contracts",
    "space": "network",
    "status": "Planned"
  },
  {
    "id": "TOP-02",
    "title": "Theater — filmmakers show films and behind-the-scenes",
    "space": "network",
    "status": "Planned"
  },
  {
    "id": "TOP-03",
    "title": "Community, with live feeds",
    "space": "network",
    "status": "Planned"
  },
  {
    "id": "TOP-04",
    "title": "Following other filmmakers",
    "space": "network",
    "status": "Planned"
  },
  {
    "id": "TOP-05",
    "title": "Streaming — free or by subscription",
    "space": "network",
    "status": "Planned"
  },
  {
    "id": "ENT-01",
    "title": "Internal-only configuration, enforced and asserted",
    "space": "enterprise",
    "status": "Being built"
  },
  {
    "id": "ENT-03",
    "title": "Security documentation",
    "space": "enterprise",
    "status": "Being built"
  },
  {
    "id": "ENT-04",
    "title": "Content-security posture aligned to the film industry’s regime (TPN)",
    "space": "enterprise",
    "status": "Planned"
  },
  {
    "id": "ENT-05",
    "title": "A second region",
    "space": "enterprise",
    "status": "Planned"
  },
  {
    "id": "ENT-06",
    "title": "Organization-wide audit export",
    "space": "enterprise",
    "status": "Planned"
  },
  {
    "id": "ENT-07",
    "title": "Seat and client-company capacity enforced",
    "space": "enterprise",
    "status": "Being built"
  },
  {
    "id": "WEB-01",
    "title": "TPN Blue Shield self-attestation against the MPA’s best practices",
    "space": "enterprise",
    "status": "Planned"
  },
  {
    "id": "WEB-02",
    "title": "SOC 2 Type II",
    "space": "enterprise",
    "status": "Planned"
  },
  {
    "id": "WEB-03",
    "title": "ISO 27001",
    "space": "enterprise",
    "status": "Planned"
  }
] as const
