/**
 * EVERYTHING THE WEBSITE SAYS GENRELINE DOES, as data — the input to the app
 * repository's capability register (docs/reference/capability-register.md
 * there, generated by its scripts/ops/gen-capability-register.ts).
 *
 *   npm run build && npm run start        # serve the built site on :3001
 *   npx tsx scripts/export-claims.ts --out <file.json>
 *
 * Two sources, because neither alone is the whole of what a visitor reads:
 *  · the CONTENT files — every feature with its label, the Suite's
 *    descriptions, the tools it replaces, the segments, plans, roadmap and
 *    changelog, exactly as the site's source of truth holds them;
 *  · the RENDERED pages — every element that carries a feature id, with the
 *    words a visitor reads there and the section it sits in. One feature is
 *    often described differently on different pages; the register quotes each
 *    wording rather than choosing one. Statement-heavy pages (AI, security,
 *    enterprise, production) are also captured as ordered text, because some
 *    of what they say is not a feature row (what Genreline does NOT claim).
 *
 * Nothing here interprets. The register's notes live in the app repository.
 */
import { execSync } from 'node:child_process'
import { writeFileSync } from 'node:fs'
import { chromium } from '@playwright/test'
import { FEATURES, OFF_SITE, SPACE_NAMES } from '../content/features'
import { SUITE_DETAIL, SUITE_STAGES } from '../content/suite'
import { TOOL_GROUPS } from '../content/tools'
import { COLLABORATORS, SEGMENTS } from '../content/segments'
import { PLANS, USAGE_CREDITS } from '../content/pricing'
import { ROADMAP } from '../content/roadmap'
import { CHANGELOG } from '../content/changelog'
import { PAGES } from '../content/pages'

const BASE = process.env.BASE ?? 'http://localhost:3001'
const OUT = process.argv[process.argv.indexOf('--out') + 1]
const STATEMENT_PAGES = ['/ai', '/security', '/enterprise', '/product/production', '/network', '/pricing']

async function main() {
  if (!OUT || OUT.startsWith('--')) throw new Error('usage: export-claims.ts --out <file.json>')
  const browser = await chromium.launch()
  const page = await browser.newPage({ viewport: { width: 1280, height: 900 } })
  // tsx compiles named arrow functions with esbuild's __name helper, which the page lacks.
  await page.addInitScript({ content: 'globalThis.__name = (f) => f' })
  const mentions: { page: string; id: string; heading: string; text: string }[] = []
  const statements: Record<string, { tag: string; text: string }[]> = {}
  for (const p of PAGES) {
    const res = await page.goto(BASE + p.path, { waitUntil: 'networkidle' })
    if (!res || res.status() !== 200) throw new Error(`${p.path} answered ${res?.status()}`)
    const found = await page.evaluate(() => {
      // The RENDERED text, line by line (innerText keeps the layout's breaks,
      // which textContent runs together), with the badges set aside.
      const lines = (el: HTMLElement) => el.innerText.split('\n').map((l) => l.replace(/\s+/g, ' ').trim()).filter(Boolean).join(' · ')
      const one = (s: string | null | undefined) => (s ?? '').replace(/\s+/g, ' ').trim()
      return Array.from(document.querySelectorAll<HTMLElement>('main [data-feature-id]:not([data-feature-label])')).map((el) => {
        const badges = Array.from(el.querySelectorAll<HTMLElement>('[data-feature-label]'))
        badges.forEach((b) => { b.dataset.exportDisplay = b.style.display; b.style.display = 'none' })
        const text = lines(el)
        badges.forEach((b) => { b.style.display = b.dataset.exportDisplay ?? '' })
        const section = el.closest('section')
        return { id: el.getAttribute('data-feature-id') ?? '', heading: one(section?.querySelector('h1, h2')?.textContent), text }
      })
    })
    const seen = new Set<string>()
    for (const m of found) {
      const key = `${m.id}|${m.text}`
      if (seen.has(key)) continue
      seen.add(key)
      mentions.push({ page: p.path, ...m })
    }
    if (STATEMENT_PAGES.includes(p.path)) {
      statements[p.path] = await page.evaluate(() => {
        const lines = (el: HTMLElement) => el.innerText.split('\n').map((l) => l.replace(/\s+/g, ' ').trim()).filter(Boolean).join(' · ')
        const out: { tag: string; text: string }[] = []
        for (const el of Array.from(document.querySelectorAll<HTMLElement>('main h1, main h2, main h3, main p, main li'))) {
          if (el.closest('[data-feature-id]')) continue
          if (el.tagName === 'P' && el.closest('li')) continue
          const text = lines(el)
          if (text && !out.some((o) => o.text === text)) out.push({ tag: el.tagName.toLowerCase(), text })
        }
        return out
      })
    }
  }
  await browser.close()

  const commit = execSync('git rev-parse --short HEAD').toString().trim()
  const dirty = execSync('git status --porcelain').toString().trim() !== ''
  const data = {
    generatedAt: new Date().toISOString(),
    website: { repository: 'McPrime-Digital/genreline-website', commit: dirty ? `${commit}+uncommitted` : commit, preview: 'https://genreline-website.vercel.app' },
    spaces: SPACE_NAMES,
    features: FEATURES.map((f) => ({ ...f, offSite: OFF_SITE.has(f.id) })),
    suite: { stages: SUITE_STAGES, detail: SUITE_DETAIL },
    tools: TOOL_GROUPS,
    segments: SEGMENTS,
    collaborators: COLLABORATORS,
    plans: PLANS,
    usageCredits: USAGE_CREDITS,
    roadmap: ROADMAP,
    changelog: CHANGELOG,
    pages: PAGES,
    mentions,
    statements,
  }
  writeFileSync(OUT, JSON.stringify(data, null, 2) + '\n')
  console.log(`wrote ${OUT}: ${data.features.length} features, ${mentions.length} rendered mentions across ${PAGES.length} pages, statements from ${Object.keys(statements).length} pages (website ${data.website.commit})`)
}
main().catch((e) => { console.error(e); process.exit(1) })
