/**
 * Generates content/roadmap.ts from content/features.ts (S-W §7.14, W-6).
 * Every row not yet built, grouped by space, with a status: "Being built"
 * (timing Launch or Next) or "Planned" (v1.5, v2, v3+). No dates. Rows that
 * are removed, excluded or undecided are not on a roadmap; Internal rows are
 * not customer-facing. Partial rows contribute their REMAINDER.
 *
 * SOC 2, ISO 27001 and the TPN self-assessment have no S-F-A row and are
 * carried as WEB-* entries because S-W §7.11 requires each gap's plan on the
 * roadmap — flagged for an S-F-A ID (FA-1).
 */
import { writeFileSync } from 'node:fs'
import { FEATURES, type Feature } from '../content/features'

const STATUS = (t: Feature['timing']) => (t === 'launch' || t === 'next' ? 'Being built' : 'Planned')

type Row = { id: string; title: string; space: string; status: 'Being built' | 'Planned' }
const rows: Row[] = []
for (const f of FEATURES) {
  if (f.status === 'built' || f.status === 'removed' || f.status === 'excluded' || f.status === 'undecided') continue
  if (f.timing === 'none' || f.timing === 'live') {
    // A Partial row that is live still carries a remainder.
    if (f.remainder) rows.push({ id: f.id, title: f.remainder, space: f.space, status: 'Planned' })
    continue
  }
  if (f.label === 'internal') continue
  if (f.id === 'DOC-04') continue // SMS passcode signing: undecided whether to build (S-F-A §13 Q3)
  rows.push({ id: f.id, title: f.remainder ?? f.title, space: f.space, status: STATUS(f.timing) })
}
rows.push(
  { id: 'WEB-01', title: 'TPN Blue Shield self-attestation against the MPA’s best practices', space: 'enterprise', status: 'Planned' },
  { id: 'WEB-02', title: 'SOC 2 Type II', space: 'enterprise', status: 'Planned' },
  { id: 'WEB-03', title: 'ISO 27001', space: 'enterprise', status: 'Planned' },
)

const out = `/* GENERATED by scripts/gen-roadmap.ts from content/features.ts — do not edit. ${new Date().toISOString().slice(0, 10)} */
export type RoadmapRow = { id: string; title: string; space: string; status: 'Being built' | 'Planned' }
export const ROADMAP: readonly RoadmapRow[] = ${JSON.stringify(rows, null, 2)} as const
`
writeFileSync('content/roadmap.ts', out)
console.log(`roadmap: ${rows.length} rows`)
